### ISSUE TITLE
ICS Calendar for Kyiv Electrical Grid Outage

### ISSUE THREAD

**Issue by ALERTua** [denysdovhan/home-assistant-config#2]
Пропоную заюзати інтеграцію ICS календаря відключень від ДТЕК на базі https://github.com/franc6/ics_calendar та https://shutdown-calendar.fly.dev

```yaml
ics_calendar:
  calendars:
    - name: Group 1
      url: "https://shutdown-calendar.fly.dev/calendar/1.ics"
      download_interval: 480
    - name: Group 2
      url: "https://shutdown-calendar.fly.dev/calendar/2.ics"
      download_interval: 480
    - name: Group 3
      url: "https://shutdown-calendar.fly.dev/calendar/3.ics"
      download_interval: 480
    - name: Group 4
      url: "https://shutdown-calendar.fly.dev/calendar/4.ics"
      download_interval: 480
```
Але в новій системі груп моя адреса — група №3, а в календарі це чомусь друга група. Мабуть розробник не оновив нумерацію. Але відстежити нумерацію своєї групи в цьому ICS календарі досить легко: достатньо додати всі чотири групи, і, вмикаючи по одній у вкладці Calendar в HA, звірити групу зі своїм графіком.

На базі цього можна створювати сценарії сповіщення про наближення відключення. Наприклад

```yaml
alias: power_outage_5min
description: ""
trigger:
  - platform: calendar
    event: start
    offset: "-0:5:30"
    entity_id: calendar.group_2
condition:
  - condition: and
    conditions:
      - condition: state
        entity_id: input_boolean.power_outage_calendar
        state: "on"
action:
  - service: pyscript.broadcast_optional
    data:
      message: >-
        Відключення електроенергії може відбутися за п'ять хвилин. Варто
        закип'ятити воду та перевірити ролети.
      language: ua
      player_ids:
        - media_player.broadcast
mode: single
```

Я пітоніст, то ж в мене 95% на [pyscript](https://github.com/custom-components/pyscript). Ця інтеграція — єдина, яка зроблена на YAML + UI конструктор, і то лише через баг в pyscript з обробкою івентів caltndar.start, який я не захотів обходити :)

Найкращі побажання від колеги тулз девелопера :)
